/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Modelo.Usuario;  
import Enums.RolUsuario;
/**
 *
 * @author Joan
 */
public class MenuPrincipal extends javax.swing.JFrame {
 private Usuario usuarioActual;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(Usuario usuario) {
        initComponents();
        this.usuarioActual = usuario;
        configurarVentana();
        mostrarInformacionUsuario();
        configurarPermisos();
    }
private void configurarVentana() {
    setLocationRelativeTo(null);
    setExtendedState(MAXIMIZED_BOTH);
}

private void mostrarInformacionUsuario() {
    lblUsuario.setText("Usuario: " + usuarioActual.getNombreCompleto());
    lblRol.setText("  |  Rol: " + usuarioActual.getRol().getDescripcion());
}

private void configurarPermisos() {
     if (usuarioActual.getRol() == RolUsuario.VENDEDOR) {
            menuUsuarios.setEnabled(false);
    }
}

public void abrirVentanaInterna(javax.swing.JInternalFrame ventana) {
    desktopPane.removeAll();
    desktopPane.add(ventana);
    ventana.setVisible(true);
    
    try {
        ventana.setMaximum(true);
    } catch (java.beans.PropertyVetoException e) {
        System.err.println("Error al maximizar ventana: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        panelEstado = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuInventario = new javax.swing.JMenu();
        menuProductos = new javax.swing.JMenuItem();
        menuProveedores = new javax.swing.JMenuItem();
        menuCategorias = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuNuevaVenta = new javax.swing.JMenuItem();
        menuHistorial = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuGestionClientes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuUsuarios = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestion-Tienda Electronica");

        desktopPane.setBackground(new java.awt.Color(241, 242, 241));

        panelEstado.setPreferredSize(new java.awt.Dimension(0, 30));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsuario.setText("Usuario:");

        lblRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRol.setText("Rol:");

        javax.swing.GroupLayout panelEstadoLayout = new javax.swing.GroupLayout(panelEstado);
        panelEstado.setLayout(panelEstadoLayout);
        panelEstadoLayout.setHorizontalGroup(
            panelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelEstadoLayout.setVerticalGroup(
            panelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRol))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        desktopPane.setLayer(panelEstado, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                .addGap(0, 377, Short.MAX_VALUE)
                .addComponent(panelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenuInventario.setText("Inventario                            ");
        MenuInventario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuProductos.setText("Productos");
        menuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosActionPerformed(evt);
            }
        });
        MenuInventario.add(menuProductos);

        menuProveedores.setText("Proveedores");
        menuProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProveedoresActionPerformed(evt);
            }
        });
        MenuInventario.add(menuProveedores);

        menuCategorias.setText("Categorias");
        menuCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriasActionPerformed(evt);
            }
        });
        MenuInventario.add(menuCategorias);

        jMenuBar1.add(MenuInventario);

        jMenu1.setText("Ventas                                 ");

        menuNuevaVenta.setText("NuevaVenta");
        menuNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevaVentaActionPerformed(evt);
            }
        });
        jMenu1.add(menuNuevaVenta);

        menuHistorial.setText("Historial");
        jMenu1.add(menuHistorial);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clientes                                ");

        menuGestionClientes.setText("Gestion de Clientes");
        jMenu2.add(menuGestionClientes);

        jMenuBar1.add(jMenu2);

        jMenu3.setText(" ");

        jMenuItem6.setText("Usuarios");
        jMenu3.add(jMenuItem6);
        jMenu3.add(jSeparator1);

        jMenuItem7.setText("jMenuItem7");
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sistema           ");

        menuUsuarios.setText("Usuarios");
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosActionPerformed(evt);
            }
        });
        jMenu4.add(menuUsuarios);
        jMenu4.add(jSeparator2);

        menuCerrarSesion.setText("Cerrar Sesion");
        menuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarSesionActionPerformed(evt);
            }
        });
        jMenu4.add(menuCerrarSesion);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosActionPerformed
      PanelProductos panelProductos = new PanelProductos();
    abrirVentanaInterna(panelProductos);
    }//GEN-LAST:event_menuProductosActionPerformed

    private void menuProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProveedoresActionPerformed
        PanelProvedores panelProvedores = new PanelProvedores();
        abrirVentanaInterna(panelProvedores);
    }//GEN-LAST:event_menuProveedoresActionPerformed

    private void menuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarSesionActionPerformed
      int respuesta = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "¿Está seguro que desea cerrar sesión?",
        "Confirmar",
        javax.swing.JOptionPane.YES_NO_OPTION
    );
    
    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        this.dispose();
        LoginForm login = new LoginForm(null, true);
        login.setVisible(true);
    }
    }//GEN-LAST:event_menuCerrarSesionActionPerformed

    private void menuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosActionPerformed
        PanelUsuarios panelUsuarios = new PanelUsuarios();
        abrirVentanaInterna(panelUsuarios);
    }//GEN-LAST:event_menuUsuariosActionPerformed

    private void menuNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevaVentaActionPerformed
        panelVentas panel = new panelVentas();
        abrirVentanaInterna(panel);
    }//GEN-LAST:event_menuNuevaVentaActionPerformed

    private void menuCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriasActionPerformed
        panelCategoria panel = new panelCategoria();
        abrirVentanaInterna(panel);
    }//GEN-LAST:event_menuCategoriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuInventario;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem menuCategorias;
    private javax.swing.JMenuItem menuCerrarSesion;
    private javax.swing.JMenuItem menuGestionClientes;
    private javax.swing.JMenuItem menuHistorial;
    private javax.swing.JMenuItem menuNuevaVenta;
    private javax.swing.JMenuItem menuProductos;
    private javax.swing.JMenuItem menuProveedores;
    private javax.swing.JMenuItem menuUsuarios;
    private javax.swing.JPanel panelEstado;
    // End of variables declaration//GEN-END:variables
}
