/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Modelo.Usuario;  
import Enums.RolUsuario;
import Utilidades.MonitorStockBajo;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import Utilidades.ConexionBD;
import java.awt.FlowLayout;
import java.awt.Component;
import javax.swing.SwingConstants;


/**
 *
 * @author Joan
 */
public class MenuPrincipal extends javax.swing.JFrame {
 private Usuario usuarioActual;
  private MonitorStockBajo monitorStock; 

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(Usuario usuario) {
        initComponents();
        this.usuarioActual = usuario;
        configurarVentana();
        mostrarInformacionUsuario();
        configurarPermisos();
        centrarContenidoTarjetas();
        centrarTitulosPrincipales();
        jPanelTarjetas.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 10));
        monitorStock = new MonitorStockBajo(this, 60);
        monitorStock.start();
        System.out.println("Monitor de stock iniciado");

        actualizarEstadisticas();
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent e) {
                actualizarEstadisticas();
            }

            public void windowLostFocus(java.awt.event.WindowEvent e) {
            }
        });
    }

    private void configurarVentana() {
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

private void mostrarInformacionUsuario() {
    lblUsuario.setText("Usuario: " + usuarioActual.getNombreCompleto());
    lblRol.setText("  |  Rol: " + usuarioActual.getRol().getDescripcion());
}

private void configurarPermisos() {
     if (usuarioActual.getRol() == RolUsuario.VENDEDOR) {
            menuUsuarios.setEnabled(false);
    }
}

public void abrirVentanaInterna(javax.swing.JInternalFrame ventana) {
    desktopPane.removeAll();
    desktopPane.add(ventana);
    ventana.setVisible(true);
    
    try {
        ventana.setMaximum(true);
    } catch (java.beans.PropertyVetoException e) {
        System.err.println("Error al maximizar ventana: " + e.getMessage());
    }
}

private void centrarContenidoTarjetas() {
    
    lblIcono1.setAlignmentX(Component.CENTER_ALIGNMENT);
    lblIcono1.setHorizontalAlignment(SwingConstants.CENTER);
    lblNumero1.setAlignmentX(Component.CENTER_ALIGNMENT);
    lblNumero1.setHorizontalAlignment(SwingConstants.CENTER);
    lblTexto1.setAlignmentX(Component.CENTER_ALIGNMENT);
    lblTexto1.setHorizontalAlignment(SwingConstants.CENTER);
    
  
    lblIcono2.setAlignmentX(Component.CENTER_ALIGNMENT);
    lblIcono2.setHorizontalAlignment(SwingConstants.CENTER);
    lblNumero2.setAlignmentX(Component.CENTER_ALIGNMENT);
    lblNumero2.setHorizontalAlignment(SwingConstants.CENTER);
    lblTexto2.setAlignmentX(Component.CENTER_ALIGNMENT);
    lblTexto2.setHorizontalAlignment(SwingConstants.CENTER);
    
    
    lblIcono3.setAlignmentX(Component.CENTER_ALIGNMENT);
    lblIcono3.setHorizontalAlignment(SwingConstants.CENTER);
    lblNumero3.setAlignmentX(Component.CENTER_ALIGNMENT);
    lblNumero3.setHorizontalAlignment(SwingConstants.CENTER);
    lblTexto3.setAlignmentX(Component.CENTER_ALIGNMENT);
    lblTexto3.setHorizontalAlignment(SwingConstants.CENTER);
    
    
    lblIcono4.setAlignmentX(Component.CENTER_ALIGNMENT);
    lblIcono4.setHorizontalAlignment(SwingConstants.CENTER);
    lblNumero4.setAlignmentX(Component.CENTER_ALIGNMENT);
    lblNumero4.setHorizontalAlignment(SwingConstants.CENTER);
    lblTexto4.setAlignmentX(Component.CENTER_ALIGNMENT);
    lblTexto4.setHorizontalAlignment(SwingConstants.CENTER);
}

private void centrarTitulosPrincipales() {
    jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
    
    jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelEstado = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        jPanelCentral = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelTarjetas = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanelTarjeta1 = new javax.swing.JPanel();
        lblIcono1 = new javax.swing.JLabel();
        lblNumero1 = new javax.swing.JLabel();
        lblTexto1 = new javax.swing.JLabel();
        jPanelTarjeta2 = new javax.swing.JPanel();
        lblIcono2 = new javax.swing.JLabel();
        lblNumero2 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        jPanelTarjeta3 = new javax.swing.JPanel();
        lblIcono3 = new javax.swing.JLabel();
        lblNumero3 = new javax.swing.JLabel();
        lblTexto3 = new javax.swing.JLabel();
        jPanelTarjeta4 = new javax.swing.JPanel();
        lblIcono4 = new javax.swing.JLabel();
        lblNumero4 = new javax.swing.JLabel();
        lblTexto4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuInventario = new javax.swing.JMenu();
        menuProductos = new javax.swing.JMenuItem();
        menuProveedores = new javax.swing.JMenuItem();
        menuCategorias = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuNuevaVenta = new javax.swing.JMenuItem();
        menuHistorial = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuGestionClientes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuUsuarios = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestion-Tienda Electronica");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        desktopPane.setBackground(new java.awt.Color(241, 242, 241));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Tienda Electrónica");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        panelEstado.setPreferredSize(new java.awt.Dimension(0, 30));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsuario.setText("Usuario:");

        lblRol.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRol.setText("Rol:");

        javax.swing.GroupLayout panelEstadoLayout = new javax.swing.GroupLayout(panelEstado);
        panelEstado.setLayout(panelEstadoLayout);
        panelEstadoLayout.setHorizontalGroup(
            panelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelEstadoLayout.setVerticalGroup(
            panelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstadoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRol))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenido al sistema");

        jPanelTarjetas.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        jPanelTarjeta1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        jPanelTarjeta1.setLayout(new javax.swing.BoxLayout(jPanelTarjeta1, javax.swing.BoxLayout.LINE_AXIS));

        lblIcono1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 36)); // NOI18N
        lblIcono1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcono1.setText("📦");
        jPanelTarjeta1.add(lblIcono1);

        lblNumero1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblNumero1.setForeground(new java.awt.Color(51, 51, 255));
        lblNumero1.setText("47");
        jPanelTarjeta1.add(lblNumero1);

        lblTexto1.setForeground(new java.awt.Color(102, 102, 102));
        lblTexto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto1.setText("Productos");
        jPanelTarjeta1.add(lblTexto1);

        jPanelTarjeta2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 102), 3));
        jPanelTarjeta2.setLayout(new javax.swing.BoxLayout(jPanelTarjeta2, javax.swing.BoxLayout.LINE_AXIS));

        lblIcono2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 36)); // NOI18N
        lblIcono2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcono2.setText(" 👥");
        jPanelTarjeta2.add(lblIcono2);

        lblNumero2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblNumero2.setForeground(new java.awt.Color(51, 255, 153));
        lblNumero2.setText("23");
        jPanelTarjeta2.add(lblNumero2);

        lblTexto2.setForeground(new java.awt.Color(102, 102, 102));
        lblTexto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto2.setText("Clientes");
        jPanelTarjeta2.add(lblTexto2);

        jPanelTarjeta3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 3));
        jPanelTarjeta3.setLayout(new javax.swing.BoxLayout(jPanelTarjeta3, javax.swing.BoxLayout.LINE_AXIS));

        lblIcono3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 36)); // NOI18N
        lblIcono3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcono3.setText("🛒");
        jPanelTarjeta3.add(lblIcono3);

        lblNumero3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblNumero3.setForeground(new java.awt.Color(255, 153, 0));
        lblNumero3.setText("156");
        jPanelTarjeta3.add(lblNumero3);

        lblTexto3.setForeground(new java.awt.Color(102, 102, 102));
        lblTexto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto3.setText("Ventas");
        jPanelTarjeta3.add(lblTexto3);

        jPanelTarjeta4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 51, 255), 3));
        jPanelTarjeta4.setLayout(new javax.swing.BoxLayout(jPanelTarjeta4, javax.swing.BoxLayout.LINE_AXIS));

        lblIcono4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 36)); // NOI18N
        lblIcono4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcono4.setText("💰");
        jPanelTarjeta4.add(lblIcono4);

        lblNumero4.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblNumero4.setForeground(new java.awt.Color(102, 51, 255));
        lblNumero4.setText("$45,230");
        jPanelTarjeta4.add(lblNumero4);

        lblTexto4.setForeground(new java.awt.Color(102, 102, 102));
        lblTexto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto4.setText("Total Ventas");
        jPanelTarjeta4.add(lblTexto4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTarjeta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanelTarjeta2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanelTarjeta3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jPanelTarjeta4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTarjeta4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTarjeta3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTarjeta2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelTarjeta1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanelTarjetas.add(jPanel3);

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addComponent(jPanelTarjetas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTarjetas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        desktopPane.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jPanelCentral, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelCentral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);
        getContentPane().add(jSeparator3, java.awt.BorderLayout.PAGE_END);

        jMenuBar1.setBackground(new java.awt.Color(0, 102, 255));

        MenuInventario.setForeground(new java.awt.Color(255, 255, 255));
        MenuInventario.setText("Inventario                            ");
        MenuInventario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuProductos.setText("Productos");
        menuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosActionPerformed(evt);
            }
        });
        MenuInventario.add(menuProductos);

        menuProveedores.setText("Proveedores");
        menuProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProveedoresActionPerformed(evt);
            }
        });
        MenuInventario.add(menuProveedores);

        menuCategorias.setText("Categorias");
        menuCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCategoriasActionPerformed(evt);
            }
        });
        MenuInventario.add(menuCategorias);

        jMenuBar1.add(MenuInventario);

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Ventas                                 ");

        menuNuevaVenta.setText("NuevaVenta");
        menuNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevaVentaActionPerformed(evt);
            }
        });
        jMenu1.add(menuNuevaVenta);

        menuHistorial.setText("Historial");
        jMenu1.add(menuHistorial);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Clientes                                ");

        menuGestionClientes.setText("Gestion de Clientes");
        menuGestionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionClientesActionPerformed(evt);
            }
        });
        jMenu2.add(menuGestionClientes);

        jMenuBar1.add(jMenu2);

        jMenu3.setText(" ");

        jMenuItem6.setText("Usuarios");
        jMenu3.add(jMenuItem6);
        jMenu3.add(jSeparator1);

        jMenuItem7.setText("jMenuItem7");
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setText("Sistema           ");

        menuUsuarios.setText("Usuarios");
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosActionPerformed(evt);
            }
        });
        jMenu4.add(menuUsuarios);
        jMenu4.add(jSeparator2);

        menuCerrarSesion.setText("Cerrar Sesion");
        menuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarSesionActionPerformed(evt);
            }
        });
        jMenu4.add(menuCerrarSesion);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosActionPerformed
      PanelProductos panelProductos = new PanelProductos();
    abrirVentanaInterna(panelProductos);
    }//GEN-LAST:event_menuProductosActionPerformed

    private void menuProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProveedoresActionPerformed
        PanelProvedores panelProvedores = new PanelProvedores();
        abrirVentanaInterna(panelProvedores);
    }//GEN-LAST:event_menuProveedoresActionPerformed

    private void menuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarSesionActionPerformed
      int respuesta = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "¿Está seguro que desea cerrar sesión?",
        "Confirmar",
        javax.swing.JOptionPane.YES_NO_OPTION
    );
    
    if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
        this.dispose();
        LoginForm login = new LoginForm(null, true);
        login.setVisible(true);
    }
    }//GEN-LAST:event_menuCerrarSesionActionPerformed

    private void menuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosActionPerformed
        PanelUsuarios panelUsuarios = new PanelUsuarios();
        abrirVentanaInterna(panelUsuarios);
    }//GEN-LAST:event_menuUsuariosActionPerformed

    private void menuNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevaVentaActionPerformed
        panelVentas panel = new panelVentas();
        abrirVentanaInterna(panel);
    }//GEN-LAST:event_menuNuevaVentaActionPerformed


    private void menuGestionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionClientesActionPerformed
        PanelClientes panelClientes = new PanelClientes();
        abrirVentanaInterna(panelClientes);
    }//GEN-LAST:event_menuGestionClientesActionPerformed

    private void menuCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCategoriasActionPerformed
        panelCategoria panel = new panelCategoria();
        abrirVentanaInterna(panel);
    }//GEN-LAST:event_menuCategoriasActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
 if (monitorStock != null) {
        monitorStock.detener();
    }
    System.exit(0);
    }//GEN-LAST:event_formWindowClosing
private void actualizarEstadisticas() {
    try {
        Connection conn = ConexionBD.getInstancia().getConexion();
        
        PreparedStatement ps = conn.prepareStatement("SELECT COUNT(*) FROM Productos WHERE estado = 1");
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            lblNumero1.setText(String.valueOf(rs.getInt(1)));
        }
        rs.close();
        ps.close();
        
        ps = conn.prepareStatement("SELECT COUNT(*) FROM Clientes WHERE estado = 1");
        rs = ps.executeQuery();
        if (rs.next()) {
            lblNumero2.setText(String.valueOf(rs.getInt(1)));
        }
        rs.close();
        ps.close();
        
        ps = conn.prepareStatement("SELECT COUNT(*) FROM Ventas WHERE estado = 'COMPLETADA'");
        rs = ps.executeQuery();
        if (rs.next()) {
            lblNumero3.setText(String.valueOf(rs.getInt(1)));
        }
        rs.close();
        ps.close();
        
        ps = conn.prepareStatement(
            "SELECT COALESCE(SUM(dv.cantidad * dv.precio_unitario * 1.13), 0) " +
            "FROM Detalle_ventas dv " +
            "JOIN Ventas v ON dv.id_venta = v.id_venta " +
            "WHERE v.estado = 'COMPLETADA'"
        );
        rs = ps.executeQuery();
        if (rs.next()) {
            lblNumero4.setText(String.format("$%.0f", rs.getDouble(1)));
        }
        rs.close();
        ps.close();
        
    } catch (SQLException e) {
        System.err.println("Error al actualizar estadísticas: " + e.getMessage());
    }
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuInventario;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelTarjeta1;
    private javax.swing.JPanel jPanelTarjeta2;
    private javax.swing.JPanel jPanelTarjeta3;
    private javax.swing.JPanel jPanelTarjeta4;
    private javax.swing.JPanel jPanelTarjetas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblIcono1;
    private javax.swing.JLabel lblIcono2;
    private javax.swing.JLabel lblIcono3;
    private javax.swing.JLabel lblIcono4;
    private javax.swing.JLabel lblNumero1;
    private javax.swing.JLabel lblNumero2;
    private javax.swing.JLabel lblNumero3;
    private javax.swing.JLabel lblNumero4;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel lblTexto3;
    private javax.swing.JLabel lblTexto4;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem menuCategorias;
    private javax.swing.JMenuItem menuCerrarSesion;
    private javax.swing.JMenuItem menuGestionClientes;
    private javax.swing.JMenuItem menuHistorial;
    private javax.swing.JMenuItem menuNuevaVenta;
    private javax.swing.JMenuItem menuProductos;
    private javax.swing.JMenuItem menuProveedores;
    private javax.swing.JMenuItem menuUsuarios;
    private javax.swing.JPanel panelEstado;
    // End of variables declaration//GEN-END:variables
}
