/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorVentas;
import Modelo.DetalleVentas;
import Modelo.Ventas;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import Utilidades.ConexionBD;
import Utilidades.GeneradorPDF;
import java.util.List;

/**
 *
 * @author Braya
 */

public class panelVentas extends javax.swing.JInternalFrame implements IVista{
    private ControladorVentas controlador;
    private Timer timer;
    private int frame = 1;
    
    /**
     * Creates new form panelVentas
     */
    public panelVentas() {
        initComponents();
        lblVenta.setSize(120, 120);
        this.controlador = new ControladorVentas(this);
        cargarVentas();
        iniciarAnimacion();
    }

    private void iniciarAnimacion() {
        timer = new javax.swing.Timer(1800, e -> animarVenta());
        timer.start();
    }

    private void animarVenta() {
        String ruta = "/VistaIconos/venta" + frame + ".png";
        java.net.URL imgURL = getClass().getResource(ruta);
        if (imgURL != null) {
            ImageIcon icon = new ImageIcon(imgURL);
            java.awt.Image img = icon.getImage().getScaledInstance(
                    lblVenta.getWidth(),
                    lblVenta.getHeight(),
                    java.awt.Image.SCALE_SMOOTH
            );
            lblVenta.setIcon(new ImageIcon(img));
        }
        frame++;
        if (frame > 4) {
            frame = 1;
        }
    }

    private void cargarVentas() {
        DefaultTableModel modelo = (DefaultTableModel) tablaVentas.getModel();
        modelo.setRowCount(0);

        Connection conn = ConexionBD.getInstancia().getConexion();

        double totalMonto = 0;
        int totalVentas = 0;

        try {
            String sql = "SELECT v.id_venta, v.fecha_venta, c.nombre_completo AS cliente, "
                    + "u.nombre_usuario AS usuario, v.observaciones, v.estado " //
                    + "FROM Ventas v "
                    + "INNER JOIN Clientes c ON v.id_cliente = c.id_cliente "
                    + "INNER JOIN Usuarios u ON v.id_usuario = u.id_usuario "
                    + "ORDER BY v.id_venta DESC";

            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                int idVenta = rs.getInt("id_venta");
                String fecha = rs.getString("fecha_venta");
                String cliente = rs.getString("cliente");
                String usuario = rs.getString("usuario");
                String observaciones = rs.getString("observaciones");  
                String estado = rs.getString("estado");

                double subtotal = calcularSubtotalVenta(idVenta);
                double iva = subtotal * 0.13;
                double total = subtotal + iva;

                modelo.addRow(new Object[]{
                    idVenta,
                    fecha,
                    cliente,
                    usuario,
                    subtotal,
                    iva,
                    total,
                    observaciones, 
                    estado
                });

                if ("Completada".equals(estado)) {
                    totalMonto += total;
                    totalVentas++;
                }
            }

            rs.close();
            stmt.close();

            lblCantidadTotalVentas.setText(String.valueOf(totalVentas));
            lblCantidadMontoTotal.setText(String.format("%.2f", totalMonto));

        } catch (SQLException e) {
            mostrarError("Error al cargar ventas: " + e.getMessage());
        }
    }

    private double calcularSubtotalVenta(int idVenta) {
        double subtotal = 0;
        Connection conn = ConexionBD.getInstancia().getConexion();

        try {
            String sql = "SELECT cantidad, precio_unitario FROM DetalleVentas WHERE id_venta = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idVenta);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                subtotal += rs.getInt("cantidad") * rs.getDouble("precio_unitario");
            }

            rs.close();
            ps.close();

        } catch (SQLException e) {
            System.err.println("Error al calcular subtotal: " + e.getMessage());
        }

        return subtotal;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelSuperior = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnActualizarVenta = new javax.swing.JButton();
        btnGenerarFactura = new javax.swing.JButton();
        btnCancelarVenta = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        TablaVentas = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblCantidadTotalVentas = new javax.swing.JLabel();
        lblMontoTotal = new javax.swing.JLabel();
        lblCantidadMontoTotal = new javax.swing.JLabel();
        lblTotalVentas = new javax.swing.JLabel();
        panelAnimacion = new javax.swing.JPanel();
        lblVenta = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setTitle("Sistema de Ventas - Panel Ventas");

        panelSuperior.setBackground(new java.awt.Color(0, 204, 204));
        panelSuperior.setPreferredSize(new java.awt.Dimension(180, 130));
        panelSuperior.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 102));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Gestion de Ventas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 124, 0, 0);
        panelSuperior.add(lblTitulo, gridBagConstraints);

        btnGuardar.setBackground(new java.awt.Color(51, 204, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Nueva Venta");
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 43, 0);
        panelSuperior.add(btnGuardar, gridBagConstraints);

        btnActualizarVenta.setBackground(new java.awt.Color(0, 0, 255));
        btnActualizarVenta.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnActualizarVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarVenta.setText("Actualizar Venta");
        btnActualizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarVentaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 17, 43, 0);
        panelSuperior.add(btnActualizarVenta, gridBagConstraints);

        btnGenerarFactura.setBackground(new java.awt.Color(255, 102, 51));
        btnGenerarFactura.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnGenerarFactura.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarFactura.setText("Generar Factura");
        btnGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarFacturaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 43, 0);
        panelSuperior.add(btnGenerarFactura, gridBagConstraints);

        btnCancelarVenta.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelarVenta.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCancelarVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarVenta.setText("Cancelar Venta");
        btnCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVentaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 32, 43, 0);
        panelSuperior.add(btnCancelarVenta, gridBagConstraints);

        btnBuscar.setBackground(new java.awt.Color(204, 0, 153));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar Venta");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 21, 43, 4);
        panelSuperior.add(btnBuscar, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 95, 0, 0);
        panelSuperior.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 76;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 21, 0, 4);
        panelSuperior.add(txtBuscar, gridBagConstraints);

        getContentPane().add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        TablaVentas.setForeground(new java.awt.Color(153, 0, 153));
        TablaVentas.setPreferredSize(new java.awt.Dimension(10, 10));

        tablaVentas.setBackground(new java.awt.Color(0, 153, 255));
        tablaVentas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Venta", "Fecha", "Cliente", "Usuario", "Subtotal", "IVA (13%)", "Total ", "Observaciones", "Estado "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVentas.setGridColor(new java.awt.Color(153, 153, 153));
        tablaVentas.setRowHeight(30);
        tablaVentas.setShowGrid(true);
        TablaVentas.setViewportView(tablaVentas);

        getContentPane().add(TablaVentas, java.awt.BorderLayout.CENTER);

        lblTitulo1.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTitulo1.setForeground(new java.awt.Color(0, 0, 102));
        lblTitulo1.setText("Gestion de Ventas");

        lblCantidadTotalVentas.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblCantidadTotalVentas.setText("0");

        lblMontoTotal.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblMontoTotal.setText("Monto Total: $");

        lblCantidadMontoTotal.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblCantidadMontoTotal.setText("0.00");
        lblCantidadMontoTotal.setToolTipText("");

        lblTotalVentas.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblTotalVentas.setText("Total de ventas");

        panelAnimacion.setOpaque(false);
        panelAnimacion.setPreferredSize(new java.awt.Dimension(160, 0));

        lblVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaIconos/venta3.png"))); // NOI18N

        javax.swing.GroupLayout panelAnimacionLayout = new javax.swing.GroupLayout(panelAnimacion);
        panelAnimacion.setLayout(panelAnimacionLayout);
        panelAnimacionLayout.setHorizontalGroup(
            panelAnimacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnimacionLayout.createSequentialGroup()
                .addComponent(lblVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelAnimacionLayout.setVerticalGroup(
            panelAnimacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnimacionLayout.createSequentialGroup()
                .addComponent(lblVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTotalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lblCantidadTotalVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblCantidadMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(panelAnimacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalVentas)
                            .addComponent(lblCantidadTotalVentas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMontoTotal)
                            .addComponent(lblCantidadMontoTotal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(panelAnimacion, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        DialogoVentas dialogo = new DialogoVentas(parentFrame, true);
        dialogo.setVisible(true);

        cargarVentas();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVentaActionPerformed
        int fila = tablaVentas.getSelectedRow();
        
        if (fila < 0) {
            mostrarError("Seleccione una venta para cancelar");
            return;
        }
        
        int idVenta = (int) tablaVentas.getValueAt(fila, 0);
        String estadoActual = (String) tablaVentas.getValueAt(fila, 7);
        
        if ("Cancelada".equals(estadoActual)) {
            mostrarError("Esta venta ya está cancelada");
            return;
        }
        
        boolean confirma = confirmar("¿Está seguro de cancelar la venta #" + idVenta + "?", "Confirmar Cancelación");
        if (!confirma) {
            return;
        }
        
        try {
            boolean exito = controlador.cancelarVentas(idVenta);
            if (exito) {
                cargarVentas();
            }
        } catch (Exception e) {
            mostrarError("Error al cancelar venta: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCancelarVentaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String idTexto = txtBuscar.getText().trim();

        if (idTexto.isEmpty()) {
            cargarVentas();
            return;
        }

        try {
            int idVenta = Integer.parseInt(idTexto);

            DefaultTableModel modelo = (DefaultTableModel) tablaVentas.getModel();
            modelo.setRowCount(0);

            Connection conn = ConexionBD.getInstancia().getConexion();

            String sql = "SELECT v.id_venta, v.fecha_venta, c.nombre_completo AS cliente, "
                    + "u.nombre_usuario AS usuario, v.observaciones, v.estado " 
                    + "FROM Ventas v "
                    + "INNER JOIN Clientes c ON v.id_cliente = c.id_cliente "
                    + "INNER JOIN Usuarios u ON v.id_usuario = u.id_usuario "
                    + "WHERE v.id_venta = ?";

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idVenta);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String fecha = rs.getString("fecha_venta");
                String cliente = rs.getString("cliente");
                String usuario = rs.getString("usuario");
                String observaciones = rs.getString("observaciones");
                String estado = rs.getString("estado");

                double subtotal = calcularSubtotalVenta(idVenta);
                double iva = subtotal * 0.13;
                double total = subtotal + iva;

                modelo.addRow(new Object[]{
                    idVenta,
                    fecha,
                    cliente,
                    usuario,
                    subtotal,
                    iva,
                    total,
                    observaciones, 
                    estado
                });
            } else {
                mostrarError("No se encontró la venta con ID: " + idVenta);
            }

            rs.close();
            ps.close();

        } catch (NumberFormatException e) {
            mostrarError("El ID debe ser un número");
        } catch (SQLException e) {
            mostrarError("Error al buscar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarVentaActionPerformed
        int fila = tablaVentas.getSelectedRow();

        if (fila < 0) {
            mostrarError("Seleccione una venta");
            return;
        }

        int idVenta = (int) tablaVentas.getValueAt(fila, 0);

        String nuevasObservaciones = solicitar("Nuevas observaciones:", "Actualizar");

        if (nuevasObservaciones != null && !nuevasObservaciones.trim().isEmpty()) {
            boolean exito = controlador.actualizarObservaciones(idVenta, nuevasObservaciones);
            if (exito) {
                cargarVentas();
            }
        }
    }//GEN-LAST:event_btnActualizarVentaActionPerformed

    private void btnGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFacturaActionPerformed
        int fila = tablaVentas.getSelectedRow();

        if (fila < 0) {
            mostrarError("Seleccione una venta para generar la factura");
            return;
        }

        int idVenta = (int) tablaVentas.getValueAt(fila, 0);
        String nombreCliente = (String) tablaVentas.getValueAt(fila, 2);
        String nombreUsuario = (String) tablaVentas.getValueAt(fila, 3);

        try {
            Ventas venta = controlador.buscarVentas(idVenta);
            if (venta == null) {
                mostrarError("No se encontró la venta");
                return;
            }

            List<DetalleVentas> detalles = controlador.obtenerDetallesVenta(idVenta);

            GeneradorPDF.generarFactura(venta, detalles, nombreCliente, nombreUsuario, this);

        } catch (Exception e) {
            mostrarError("Error al generar factura: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGenerarFacturaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TablaVentas;
    private javax.swing.JButton btnActualizarVenta;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelarVenta;
    private javax.swing.JButton btnGenerarFactura;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantidadMontoTotal;
    private javax.swing.JLabel lblCantidadTotalVentas;
    private javax.swing.JLabel lblMontoTotal;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTotalVentas;
    private javax.swing.JLabel lblVenta;
    private javax.swing.JPanel panelAnimacion;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTable tablaVentas;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarMensaje(String msg, String titulo) {
        javax.swing.JOptionPane.showMessageDialog(this, msg, titulo, javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void mostrarError(String msg) {
        javax.swing.JOptionPane.showMessageDialog(this, msg, "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public boolean confirmar(String msg, String titulo) {
        int result = javax.swing.JOptionPane.showConfirmDialog(this, msg, titulo, javax.swing.JOptionPane.YES_NO_OPTION);
        return result == javax.swing.JOptionPane.YES_OPTION;
    }

    @Override
    public String solicitar(String msg, String titulo) {
        return javax.swing.JOptionPane.showInputDialog(this, msg, titulo, javax.swing.JOptionPane.QUESTION_MESSAGE);
    }
}
