/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorCliente;
import java.awt.Color;
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author itsth
 */
public class PanelClientes extends javax.swing.JInternalFrame {
    private Timer timer;
    private int frame = 1;
    private ControladorCliente controlador;

    /**
     * Creates new form PanelClientes
     */
    public PanelClientes() {
        initComponents();
        tablaClientes.getTableHeader().setBackground(new java.awt.Color(25, 118, 210)); // Azul
        tablaClientes.getTableHeader().setForeground(java.awt.Color.WHITE);
        tablaClientes.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 13));
        this.controlador = new ControladorCliente(this);
        configurarEventos();
        controlador.cargarClientes();
    }
    
    private void iniciarAnimacion() {
        timer = new javax.swing.Timer(1000, e -> animarVenta());
        timer.start();
    }

    private void animarVenta() {
        String ruta = "/VistaIconos/cliente" + frame + ".png";
        java.net.URL imgURL = getClass().getResource(ruta);
        if (imgURL != null) {
            ImageIcon icon = new ImageIcon(imgURL);
           // java.awt.Image img = icon.getImage().getScaledInstance(
                    //lblCliente.getWidth(),
                    //lblCliente.getHeight(),
                  //  java.awt.Image.SCALE_SMOOTH
          //  );
            //lblCliente.setIcon(new ImageIcon(img));
        }
        frame++;
        if (frame > 4) {
            frame = 1;
        }
    }

    private void configurarEventos() {
        btnBuscar.addActionListener(e -> controlador.buscarCliente(txtBuscar.getText().trim()));
        btnAgregar.addActionListener(e -> controlador.agregarCliente());
        btnActualizar.addActionListener(e -> controlador.actualizarCliente());
        btnEliminar.addActionListener(e -> controlador.eliminarCliente());
    }

    public JTable getTablaClientes() {
        return tablaClientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();

        setTitle("Sistema Clientes");

        panelBotones.setBackground(new java.awt.Color(0, 204, 204));
        panelBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelBotones.setPreferredSize(new java.awt.Dimension(688, 150));
        panelBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setBackground(new java.awt.Color(0, 153, 51));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        panelBotones.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(255, 153, 0));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        panelBotones.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        panelBotones.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Buscar");
        panelBotones.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 15, -1, 30));
        panelBotones.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 160, 30));

        btnBuscar.setBackground(new java.awt.Color(0, 0, 204));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        panelBotones.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestion Clientes");
        panelBotones.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 194, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaIconos/floppy_disk_48.png"))); // NOI18N
        panelBotones.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaIconos/Actualizar.png"))); // NOI18N
        panelBotones.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaIconos/cancelar.png"))); // NOI18N
        panelBotones.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaIconos/Search.png"))); // NOI18N
        panelBotones.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaIconos/Buscar.png"))); // NOI18N
        panelBotones.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaIconos/cliente.png"))); // NOI18N
        panelBotones.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 60, 60));

        getContentPane().add(panelBotones, java.awt.BorderLayout.PAGE_START);

        tablaClientes.setAutoCreateRowSorter(true);
        tablaClientes.setBackground(new java.awt.Color(0, 153, 255));
        tablaClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cedula", "Nombre", "Telefono", "Email", "Direccion", "Estado", "Fecha registro"
            }
        ));
        tablaClientes.setGridColor(new java.awt.Color(135, 135, 135));
        tablaClientes.setShowGrid(true);
        jScrollPane1.setViewportView(tablaClientes);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
